parameters:
#    eifl_member.example.class: Eifl\MemberBundle\Example

services:
#    eifl_member.example:
#        class: %eifl_member.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
