parameters:
#    eifl_admin.example.class: Eifl\AdminBundle\Example

services:
#    eifl_admin.example:
#        class: %eifl_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
