<?php

namespace Eifl\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassDetailRepository extends EntityRepository
{
}
