<?php

namespace Eifl\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends EntityRepository
{
	public function findAvailableCompetition(){
		$now = new \DateTime("now");
		return $this->getEntityManager()
            ->createQuery(
                "SELECT comp FROM EiflAdminBundle:Competition comp WHERE comp.date > :now"
            )
            ->setParameter('now',$now)
            ->getResult();
	}
}