<?php

namespace Eifl\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
	public function findActiveMember(){
		return $this->getEntityManager()
            ->createQuery(
                "SELECT user FROM EiflAdminBundle:Member member LEFT JOIN EiflMainBundle:User user WHERE user.roles LIKE 'a:0:{}'"
            )
            ->getResult();
	}

	public function findMemberByName($member){
		return $this->getEntityManager()
            ->createQuery(
                "SELECT user FROM EiflAdminBundle:Member member LEFT JOIN EiflMainBundle:User user WHERE user.roles LIKE 'a:0:{}' AND user.username LIKE :member"
            )
            ->setParameter('member','%'.$member.'%')
            ->getResult();
	}
    public function findMemberByProgramAndClass($id){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT m.id FROM EiflAdminBundle:Member m LEFT JOIN EiflAdminBundle:ClassDetail cd WHERE cd.member IS NOT NULL OR cd.program != :id"
            )
            ->setParameter('id',$id)
            ->getResult();
    }
    // public function availableMember(){
    //     return $this->getEntityManager()
    //         ->createQuery(
    //             "SELECT user FROM EiflAdminBundle:Member member LEFT OUTER JOIN EiflAdminBundle:User user WHERE user.roles LIKE 'a:0:{}'"
    //         )
    //         ->getResult();
    // }
}
