<?php

namespace Eifl\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
	public function findClassTaken($admin){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT cl FROM EiflAdminBundle:ClassLevel cl INNER JOIN EiflAdminBundle:MainDetail md WHERE md.admin = :admin AND cl.id = md.class"
            )
            ->setParameter('admin',$admin)
            ->getResult();
    }
}
